export const API_ENDPOINTS = {
    AUTH: {
        SIGN_IN: '/auth/sign-in',
        SIGN_UP: '/auth/sign-up',
        LOGOUT: '/auth/logout',
        LOGOUT_ALL: '/auth/logout-all',
        ME: '/auth/me',
        REFRESH_TOKEN: '/auth/refresh-token',
        CHANGE_PASSWORD: '/auth/change-password',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
        GOOGLE_AUTH: '/auth/google',
        GOOGLE_AUTH_CALLBACK: '/auth/google/callback',
        GOOGLE_GENERATE_URL: '/auth/google/generate-url',
    },
    USERS: {
        LIST: '/users',
        PROFILE: '/users/profile',
        STATS: '/users/stats',
        BULK_UPDATE: '/users/bulk-update',
        BY_ID: (id: string) => `/users/${id}`,
        UPDATE: (id: string) => `/users/${id}`,
        DELETE: (id: string) => `/users/${id}`,
        STATUS: (id: string) => `/users/${id}/status`,
        ROLE: (id: string) => `/users/${id}/role`,
    },
    DATABASES: {
        LIST: '/databases',
        CREATE: '/databases',
        BY_ID: (id: string) => `/databases/${id}`,
        UPDATE: (id: string) => `/databases/${id}`,
        DELETE: (id: string) => `/databases/${id}`,
        SHARE: (id: string) => `/databases/${id}/share`,
        REMOVE_ACCESS: (id: string, userId: string) => `/databases/${id}/share/${userId}`,
        PROPERTIES: (id: string) => `/databases/${id}/properties`,
        PROPERTY: (id: string, propertyId: string) => `/databases/${id}/properties/${propertyId}`,
        VIEWS: (id: string) => `/databases/${id}/views`,
        VIEW: (id: string, viewId: string) => `/databases/${id}/views/${viewId}`,
        RECORDS: (id: string) => `/databases/${id}/records`,
        RECORD: (id: string, recordId: string) => `/databases/${id}/records/${recordId}`,
    },
    DASHBOARD: {
        STATS: '/dashboard/stats',
        ANALYTICS: '/dashboard/analytics',
    },
    PROFILE: {
        GET: '/profile',
        UPDATE: '/profile',
    },
} as const
